### ISSUE TITLE
File order ascending-descending

### ISSUE THREAD

**Issue by andreapx** [eneiluj/gpxpod#11]
In the new version I see the new files at the bottom.
In the option there is just the possibility to chose the field to use for ordering the files, but not if ascending or descending.
This would be very useful!
Also, the menu options scrolls with the files, I think that it should stay at the top always visible.

**Comment by julien-nc** [comment]
Thanks for the suggestion. It's now done and will be included in the next release which is coming soon.
![image](https://user-images.githubusercontent.com/11291457/229382851-191734cb-e241-4c3d-9364-909201628610.png)

The action menu scrolling can't really be avoided. It follows the element it is about. As the directory item goes away, so does the related action menu.

**Comment by julien-nc** [comment]
Feel free to reopen this issue if needed.
