### ISSUE TITLE
elevation correction error

### ISSUE THREAD

**Issue by Synochy** [eneiluj/gpxpod#12]
When using the elevation correction feature. 
The feature fails and there is the following error in the server logbook:
Optional parameter $recursive declared before required parameter $directoryId is implicitly treated as a required parameter at /var/www/nextcloud/apps/gpxpod/lib/Service/ProcessService.php#803

**Comment by julien-nc** [comment]
Thanks for the bug report. Could you try to just remove the default value for `$recursive` on `gpxpod/lib/Service/ProcessService.php` line 803?

``` php
public function getGeoPicsFromFolder(string $userId, string $subfolder, bool $recursive = false, int $directoryId): array {
```
should become
``` php
public function getGeoPicsFromFolder(string $userId, string $subfolder, bool $recursive, int $directoryId): array {
```
And then confirm the issue goes away on your side?

**Comment by Synochy** [comment]
I do not have error in the logbook anymore but the elevation correction still fails with the following message:
![image](https://user-images.githubusercontent.com/20789073/216542078-c2bfbea3-9bb8-400e-9e87-aeecc75145c1.png)

**Comment by Synochy** [comment]
Any other idea to fix the problem ?

**Comment by Synochy** [comment]
I corrected my problem by unstalling and installing again the app
