### ISSUE TITLE
New interface (beta) : default map view ("streets") is empty, white

### ISSUE THREAD

**Issue by tomchiverton** [eneiluj/gpxpod#16]

**Comment by julien-nc** [comment]
It is because the default MapTiler API key is very limited and used by everybody. How to get a MapTiler API key is explained the settings in the new interface (bottom left button).

**Comment by tomchiverton** [comment]
I have set a custom key, and it's all white. Changing to openstreetmap raster makes the map appear 
-- 
†øღ

**Comment by tomchiverton** [comment]
![Screenshot_20230326_185433](https://user-images.githubusercontent.com/684204/227794726-2c56ad2e-f681-41f1-91b1-8ded5631b66a.png)

**Comment by tomchiverton** [comment]
Think this is fixed in latest nightly, maybe a50d4d178655c6ce1c70f783513afd64d7158954 helped ?
