### ISSUE TITLE
gpxpod stopped to work

### ISSUE THREAD

**Issue by nerux1** [eneiluj/gpxpod#20]
Hello,

I use this extension since several years.
Could you help me to initialize them ?

Since 2 or 3 months this application stopped to work, if I add a folder with a GPX file : no trace available
If I click on a GPX trace, I will see only the world map.
I try old and new UI
I try to delete .geojson, .marker files, metadata, ... remove and delete the application

`{"reqId":"3Veorn6OXttRPYXWLGSM","level":3,"time":"2023-04-06T05:19:16+00:00","remoteAddr":"X.X.X.X","user":"bob","app":"index","method":"POST","url":"/apps/gpxpod/tracks-old","message":"Division by zero in file '/var/www/html/apps_w/gpxpod/lib/Service/ConversionService.php' line 291","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0","version":"26.0.0.11","exception":{"Exception":"Exception","Message":"Division by zero in file '/var/www/html/apps_w/gpxpod/lib/Service/ConversionService.php' line 291","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\GpxPod\\Controller\\OldPageController"],"getTrackMarkersText"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\GpxPod\\Controller\\OldPageController","getTrackMarkersText",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["gpxpod.oldPage.getTrackMarkersText"]]},{"file":"/var/www/html/lib/base.php","line":1055,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/gpxpod/tracks-old"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"DivisionByZeroError","Message":"Division by zero","Code":0,"Trace":[{"file":"/var/www/html/apps_w/gpxpod/lib/Service/ConversionService.php","line":272,"function":"exifCoordToNumber","class":"OCA\\GpxPod\\Service\\ConversionService","type":"->","args":["0/0"]},{"file":"/var/www/html/apps_w/gpxpod/lib/Controller/OldPageController.php","line":998,"function":"getDecimalCoords","class":"OCA\\GpxPod\\Service\\ConversionService","type":"->","args":[["0/0","0/0","0/0"],""]},{"file":"/var/www/html/apps_w/gpxpod/lib/Controller/OldPageController.php","line":563,"function":"getGeoPicsFromFolder","class":"OCA\\GpxPod\\Controller\\OldPageController","type":"->","args":["/Photos/2023/03-mars",false]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getTrackMarkersText","class":"OCA\\GpxPod\\Controller\\OldPageController","type":"->","args":["/Photos/2023/03-mars",false,false]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\GpxPod\\Controller\\OldPageController"],"getTrackMarkersText"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\GpxPod\\Controller\\OldPageController"],"getTrackMarkersText"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\GpxPod\\Controller\\OldPageController","getTrackMarkersText",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["gpxpod.oldPage.getTrackMarkersText"]]},{"file":"/var/www/html/lib/base.php","line":1055,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/gpxpod/tracks-old"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps_w/gpxpod/lib/Service/ConversionService.php","Line":291},"CustomMessage":"--"}}`

**Comment by julien-nc** [comment]
Hi, thanks for the bug report.

Could you try changing line 1039 of `gpxpod/lib/Service/ProcessService.php` from
``` php
catch (\Exception $e) {
```
to
``` php
catch (\Exception | \Throwable $e) {
```
and do the same for line 1045 of `lib/Controller/OldPageController.php`?

And then you can try reloading the old and new UI.

**Comment by nerux1** [comment]
Oh :)

Nice, it works !

Could you explain me your solution ? It is a different object type ?

Thanks for your work.

**Comment by julien-nc** [comment]
Well it's a basic mistake. The error was not handled when there's a division by zero happening in some cases with photos with invalid geotag data. It made the entire process fail. With the fix, the problematic photo is just skipped.

v5.0.9 is out and contains this fix.

Please reopen this issue if something is still wrong.

**Comment by julien-nc** [comment]
Can you confirm if v5.0.9 works on your side?

**Comment by nerux1** [comment]
Yes, I just updated the application and I confirm, It works out of the box.
I just recursively added a complete tree with about 30 traces.
