### ISSUE TITLE
New interface (Beta) is empty since 5.0.8

### ISSUE THREAD

**Issue by Synochy** [eneiluj/gpxpod#22]
Hello,

Since the 5.0.8 update, the new interface is empty : no files / no map
![image](https://user-images.githubusercontent.com/20789073/230779250-911d83fb-6f1b-4cf0-a5d1-8a34221560fe.png)

**Comment by julien-nc** [comment]
Thanks for the bug report. I need more information to figure out the reason it does not work on your side:

* Which browser are you using?
* Did you try multiple browsers?
* Do you get any error message in the browser console log?
* Do you get any GpxPod-related error in the Nextcloud server log? (nextcloud.log)
* Anything specific to your setup could help

**Comment by Synochy** [comment]
I am using using firefox 111.0.1.
I tried also on google chrome (without any addon) but I have a the same result

I am on php 8.2 and NC 26
the only error I have brower consol log is this one but I don't think it is related
![image](https://user-images.githubusercontent.com/20789073/230779970-717f42fc-c717-4705-bc56-874171fa41c5.png)

I don't have any error in Nextcloud log. I also tried to uninstall and install gpxpod.

**Comment by julien-nc** [comment]
* Any failing network request (network tab of the dev tools) when you load the GpxPod page?
* Is the old UI working fine?
* Are you sure it was working with v5.0.6?

**Comment by julien-nc** [comment]
Can you try setting a valid MapTiler API key?
You can do it with occ:
For your user:
```
occ user:setting USER_ID gpxpod maptiler_api_key API_KEY
```
Or for all users (this can also be done in the admin additional settings):
```
occ config:app:set gpxpod maptiler_api_key --value="API_KEY"
```

**Comment by Synochy** [comment]
I created an account on MapTiler to get an API key.
I use : 
`occ config:app:set gpxpod maptiler_api_key --value="API_KEY"`

And it solves the problem.
If I understand well, from now on we will need an account on MapTiler account to have the app works ?

**Comment by julien-nc** [comment]
Thanks for the feedback.

> If I understand well, from now on we will need an account on MapTiler account to have the app works ?

Not really. The raster tile servers ("OpenStreetMap raster", "ESRI" and "Watercolor") still work without MapTiler API key as they are not related.

"OpenStreetMap raster" is now the default for new users (using GpxPod for the first time).

It's weird that I can't reproduce the issue. If I load the page while having no API key or an invalid one or the default one, and the selected tile server is "Streets", everything still loads and I'm able to change the tile server afterwards. I'll dig deeper.

Anyway, what can be done to make this safer is to remove the vector tile servers from the list if no API key is set.
I'll keep you updated.
