### ISSUE TITLE
New interface: MapTiler / Custom tileservers

### ISSUE THREAD

**Issue by sgofferj** [eneiluj/gpxpod#26]
Why the choice for maptiler? It adds unnecessary hassle and privacy concerns for private users plus it severely limits the choice of maps. The missing option for custom tile servers makes GPXpod effective unusable for many regions of the world where maptiler doesn't have uptodate maps for, such as (rural) Finland.

I'd kindly ask you to reconsider that design choice.

**Comment by julien-nc** [comment]
https://github.com/julien-nc/gpxpod/blob/0fda59c359f277dbc0f4542d73756bffdb8266bb/CHANGELOG.md?plain=1#L20
