### ISSUE TITLE
Ability to draw tracks

### ISSUE THREAD

**Issue by regs01** [eneiluj/gpxpod#27]
It's probably would be a little too much to ask, but would be great if there is an ability to draw own tracks, like in Google My Maps. As far as I know KML format does allow multiple polygons and lines in a single file.

**Comment by julien-nc** [comment]
I don't get what you mean. Can you reformulate? :grin: 

KML files are converted to GPX. Maybe you mean increase the support for KML. Yeah as polygons are not a thing in the GPX format they are not drawn.

**Comment by regs01** [comment]
Draw lines and polygons and save them as a file



https://github.com/julien-nc/gpxpod/assets/10468217/5e55b416-dd37-4f98-b352-a53a7d62d381

**Comment by julien-nc** [comment]
I'm afraid this is out of this app's scope :grin: . GpxEdit (now abandoned) allowed drawing lines (but not polygons) and save them as a GPX file.
