### ISSUE TITLE
Errormessage after updating to NC 27.0

### ISSUE THREAD

**Issue by berndz2001** [eneiluj/gpxpod#29]
Hi,
i've updated to NC 27. When I click onto a gpx-file I get the message "Failed to load track geojson: " The same message appears when I reload the folder. The track is shown when I hover the filename.
Changing to the old interface, I can't download the gpx-file: ERROR File cannot be downloaded.
Regards.
Bernd

**Comment by julien-nc** [comment]
Hi,
Thanks for the bug report.
I need more information to understand what happens on your side and fix this issue.
Could you check if you get GpxPod-related lines in the server log (data/nextcloud.log)?

**Comment by berndz2001** [comment]
Hi Julien,
I solved the problem. My redisserver wasn't configured correctly. I found this: https://help.nextcloud.com/t/permission-denied-for-redis/19806. unixsocketperm was set to 700 and I changed it to 770. www-data was member of redis in /etc/group. After rebooting my server gpxpod works fine again.
Regards.
Bernd
