### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by regs01** [eneiluj/gpxpod#3]
Would it be possible to make it show speed in every point (average calculation from some of points) and a speed/distance chart?

**Comment by julien-nc** [comment]
Hey, sorry for the late answer.

In the old UI, after selecting "speed" as color criteria (in the expandable options), speed is displayed when hovering points and the bottom left graph is speed/distance.

In the new UI, the speed is always displayed when hovering points. And the chart in the track details right sidebar contains a speed graph. You can even change what's used as the X axis.

Feel free to reopen if needed.
