### ISSUE TITLE
"No folder selected" when sharing a link (and no mobile view)

### ISSUE THREAD

**Issue by nautik1** [eneiluj/gpxpod#31]
Hello and thank you for this awesome app !
I am experimenting to see what I can do with my gpx files and the "new interface" of gpxpod looks very nice.

I'd like to share some tracks with relatives, but I have a weird behavior when opening a shared link: the left panel always displays "No folder selected".
It does not matter if the link was to share a single track or a folder; track(s) are displayed on the map, but the left panel always says "No folder selected".

I guess I should have the list of track(s) and maybe stats / graphs, similarly to the connected version of the page?

On mobile, the map is not displayed and all I see is the "No folder selected" panel...

Would it be possible to have only the map displayed on mobile maybe? I'd love to be able to share with people mostly using their phone.

Just upgraded NC to 27.0.0 but I had the same behavior with 26.x.x

Have a good day,

**Comment by julien-nc** [comment]
Hey, thanks for the issue.

I made a lot of changes related to everything you mentioned. Things should be fixed and improved in public pages and in mobile view.
It would be nice to have your feedback on the next release. It's coming soon. I'll keep you informed.

**Comment by nautik1** [comment]
Sounds nice! Any news? Don't hesitate if I can help, with testing for example!

**Comment by nautik1** [comment]
@julien-nc Thanks for the 5.0.13 version which fixes everything above, it's awesome! :fireworks:

Resolving this issue!
