### ISSUE TITLE
Unable to add a directory

### ISSUE THREAD

**Issue by ventoux84** [eneiluj/gpxpod#32]
In the new interface, i can't add a directory.
GPXPod says that this directory is already selected. It has the same name, but it is in a other sub-diretory of an other directory.

Traces
- Rando
- - Ventoux
-VTT
-- Ventoux

**Comment by julien-nc** [comment]
Hey. I can't reproduce locally.

* A
    * B
        * A

I can add both A directories.
Can you describe more precisely what you do so I can try to reproduce?

**Comment by ventoux84** [comment]
I deleted all the directories displayed and then added the two with the same name.
It works ! Thanks for this very useful app.

It was certainly already selected, but the list didn't show it. Maybe there were too many
