### ISSUE TITLE
Manual installation in ownCloud 10.10.0.3 does not work

### ISSUE THREAD

**Issue by AWeidenbacher** [eneiluj/gpxpod#4]
Have downloaded the newest package into APP folder on my owncloud server. See the app in "not installed" - with activation of the app I have to start "occ upgrade" (which looks good) but afterwards owncloud did not start anymore? I have deactivated the app now with "sudo -u apache php occ app:disable gpxpod" so owncloud is running again.

Is there a solution already available? 
THX
Andreas

**Comment by tomchiverton** [comment]
Are you getting a 500 server error then ? For what page(s) ? What does the server error log say ?

**Comment by julien-nc** [comment]
For the record: ownCloud and Nextcloud have diverged too much for GpxPod to still work on ownCloud. Sorry about that.
