### ISSUE TITLE
Make app compatible with NC v25

### ISSUE THREAD

**Issue by depuits** [eneiluj/gpxpod#5]
NC25 is just released, this app is currently marked as untested. Will it be updated for version 25?

**Comment by LiloBzH** [comment]
Hello

Same question. i delete version for NC24 but the new version of this repo is not availaible

Thank you !

**Comment by p-bo** [comment]
Seems to be done (also for Nextcloud 26) - see https://apps.nextcloud.com/apps/gpxpod/releases?platform=25#26 - please close this.
