### ISSUE TITLE
Public gpxpod share doesn't load tiles

### ISSUE THREAD

**Issue by playlix42** [eneiluj/gpxpod#54]
Hi, 
I tried to use the app on my own NextCloud instance and it works great if the user is logged in. 
However, if I try to share a folder via a **public** link, the map tiles won't load, regardless which map style is used.
In the logs, I found the following message multiple times:
```json
{"reqId":"9b6OjQFCuuhXSCncJEax","level":0,"time":"2024-09-22T13:48:49+00:00","remoteAddr":"***","user":"--","app":"no app in context","method":"GET","url":"/index.php/apps/gpxpod/tiles/osm/534/337/10?s=b","message":"Current user is not logged in","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0","version":"30.0.0.14","exception":{"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException","Message":"Current user is not logged in","Code":401,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":73,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->","args":[["OCA\\GpxPod\\Controller\\MapController"],"getRasterTile"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":106,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[["OCA\\GpxPod\\Controller\\MapController"],"getRasterTile"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\GpxPod\\Controller\\MapController"],"getRasterTile"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\GpxPod\\Controller\\MapController","getRasterTile",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["osm","534","337","10","gpxpod.map.getrastertile"]]},{"file":"/var/www/html/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/gpxpod/tiles/osm/534/337/10"]},{"file":"/var/www/html/index.php","line":24,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php","Line":113,"message":"Current user is not logged in","exception":[],"CustomMessage":"Current user is not logged in"},"id":"***"}
```
I already tried to find the cause of the problem.

I think the following lines are the problem: https://github.com/julien-nc/gpxpod/blob/c067dd2dbae3c27a2b13691934a254241d485c6f/lib/Controller/MapController.php#L50-L61

I assume there could be a missing attribute for this use-case: 
https://github.com/nextcloud/server/blob/77c1db0cd64a11aa21425f663cfe9fdff988ad58/lib/public/AppFramework/Http/Attribute/PublicPage.php#L14-L21

Could this be a security issue? What do you think, maybe you can fix this?
Thanks in advance!

**Comment by julien-nc** [comment]
Thanks for reporting this issue. This is now fixed.
The tile requests are proxied through the NC server. This uses endpoints that require to be connected. We could have made them public but I chose to not proxy anything in public pages. The tile servers are now accessed directly by the browser in public pages.
The fix will be included in the next release which is coming soon.

**Comment by simonmicro** [comment]
Thanks @julien-nc - but if requests are not proxied anymore, doesn't this mean, that the token for the tile service will be shared with the browser, so it can access them? So, it will be leaked now? Sorry, I have no time to take a look at your changes - maybe I'm just wrong.

Maybe a better alternative would be to still proxy this endpoint, but heavily rate-limit it. Also showing a warning inside the UI, that requests are limited without login?

Thanks!

**Comment by julien-nc** [comment]
They keys are leaked even when the requests are proxied. I'm not sure I want to change this. The key is always sent to the frontend (private and public pages) which uses it for the proxy URL or the direct ones. I wanna keep this consistency.

The solution to prevent others to use your key is to set the `Allowed HTTP Origins` in https://cloud.maptiler.com/account/keys/new

I will make sure both proxied and direct requests work when a key is limited to the domain of a Nextcloud instance. I'll make some tests after adding the `Origin` header to all proxied requests.

**Comment by julien-nc** [comment]
It works like a charm. Using the `Allowed HTTP Origins` API key restriction, one can make sure the key can only be used by the frontend and the backend of their Nextcloud instance. The proxy now adds a `Origin: NC_BASE_URL` HTTP header to all proxy requests.

**Comment by playlix42** [comment]
Thank you very much for fixing this issue 👍
