### ISSUE TITLE
Backport the speed timeline

### ISSUE THREAD

**Issue by StefLedof** [eneiluj/gpxpod#55]
Hello, 

Backport de speed timeline in version 7

Thank

Stéphane

**Comment by julien-nc** [comment]
Hi,
I'm not sure what you mean.
If you open the details for a track and switch to the "Charts" sidebar tab, you can see
![image](https://github.com/user-attachments/assets/473be8ba-8d65-4afd-a29a-021c52c26baf)

**Comment by StefLedof** [comment]
Hello Julien, 
That's it. I hadn't figured out how to access it.
Thank
Stéphane
