### ISSUE TITLE
No map tiles in new interface

### ISSUE THREAD

**Issue by creideiki** [eneiluj/gpxpod#61]
After switching to the new interface (forced with the upgrade to NextCloud 30), I get no map tiles at all in GpxPod. Tracks and icons are drawn, but where I expect map tiles the window is white (and GitHub doesn't allow me to attach a screenshot, for some reason).

I have tried all the different renderers, including the ones [supposed to work without API keys](https://github.com/julien-nc/gpxpod/issues/22#issuecomment-1502861053).

When using the OpenStreetMap raster renderer, Firefox's network debugger shows lots of failed calls to `https://MY-NEXTCLOUD-SERVER/nextcloud/index.php/apps/gpxpod/tiles/osm/COORD/COORD/ZOOM` . I have not specified a custom tile server in the GpxPod settings, so I don't understand why the frontend tries to ask my own server for data it cannot have.

**Comment by julien-nc** [comment]
Thanks for the bug report. I need more details on the errors you see in the browser logs and the network errors in the network tab.

**Comment by julien-nc** [comment]
> so I don't understand why the frontend tries to ask my own server for data it cannot have

The tile requests are proxied through Nextcloud.

**Comment by creideiki** [comment]
> The tile requests are proxied through Nextcloud.

Well, that's a problem. My server is behind a firewall that does not allow it to make outgoing HTTP connections.

Is there a way to configure the frontend to get the tiles itself instead of going through the NextCloud server?

**Comment by julien-nc** [comment]
I will add that option and include it in the next release.

**Comment by julien-nc** [comment]
v7.0.1 is out. I'm interested to know if all works fine on your side.

**Comment by creideiki** [comment]
> v7.0.1 is out. I'm interested to know if all works fine on your side.

Yes, thank you! I can now get the "OpenStreetMap raster" and "ESRI topo with relief" map tiles, which is enough for my use case.

**Comment by julien-nc** [comment]
Thanks for the feedback.
