### ISSUE TITLE
Cannot activate gpxpod app in nextcloud 30.0.1

### ISSUE THREAD

**Issue by AlterDepp** [eneiluj/gpxpod#62]
I updated nextcloud from 29 to 30.0.1 (via docker-compose). The gpxpod app was disabled. When I try to activate the app again I get an error message in the updater:

> Database error when running migration 070002Date2024102060425 for app gpxpod An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '_path/to/dir_' for key 'gpxpod_dir_user_path_uniq'

In the log I have many entries like:

> AutoloadNotAllowedException Autoload path not allowed: /var/www/html/custom_apps/gpxedit/appinfo/application.php
> Error during app loading: Autoload path not allowed: /var/www/html/custom_apps/gpxedit/appinfo/application.php

**Comment by julien-nc** [comment]
Thanks for reporting this issue. I'll try to fix that in the next release. In the meantime, if you have direct access to the database, you can just delete the rows pointing to the same "path" for the same "user".

**Comment by julien-nc** [comment]
I made a fix. I tested it successfully on my side but it would be nice if you could confirm it works. I will then make a new release.
This is an alternative to my previous comment. No need to remove duplicates manually to try this solution. Just replace the content of `apps/gpxpod/lib/Migration/Version070002Date20241020160425.php` with the one of https://github.com/julien-nc/gpxpod/blob/fix/62/remove-duplicates-before-adding-unique-constraint/lib/Migration/Version070002Date20241020160425.php
The migration should then run fine and take care of removing the duplicates. It should then create the unique constraint successfully.

**Comment by AlterDepp** [comment]
The fix worked for me. Thanks for fast service.

**Comment by julien-nc** [comment]
Thanks for the feedback. Which solution did you take? Manually deleting the rows or replacing the content of `Version070002Date20241020160425.php`?

**Comment by AlterDepp** [comment]
The second one with the fix.
